### ISSUE TITLE
Support React 18 

### ISSUE THREAD

**Issue by owlet1997** [react-buddy/ide-toolbox#27]
Create-react-app template was updated and now the 18 react and react-dom version is used there:
![image](https://user-images.githubusercontent.com/45730069/161515324-d8e58218-480b-423e-be63-b3e9e9a65c6f.png)

dependencies conflict is appearing:
![image](https://user-images.githubusercontent.com/45730069/161515137-b82237d8-89a4-4faa-8f23-2895cbcded67.png)

**Comment by web-devel** [comment]
It seems there is another gotcha with types:
https://github.com/react-buddy/ide-toolbox/issues/27
