### ISSUE TITLE
Palette preview width shrinking

### ISSUE THREAD

**Issue by web-devel** [react-buddy/ide-toolbox#36]
Investigate layout styling in component preview and make sure the content occupies 100% of width
<img width="914" alt="image" src="https://user-images.githubusercontent.com/3295727/183414939-d7d611bf-1122-4d9b-b7a4-2530d3336ec8.png">

See https://github.com/react-buddy/demo-antd-v4
* Grid
* Timeline (mode right) 

## Suggested implementation
* introduce `previewLayout: 'center' | 'stretch'` prop in `Variant`
* `center` is the default value (if prop is not specified)

**Comment by lovtsovaik** [comment]
Also need to fix Carousel (big size of layout)

**Comment by HegelPro** [comment]
Every dom element from Component's dom element to the html element must have "fullWindow" class once.
And our className prop which we setted to Palette, Category, Component or Variant must be last in dom classes.
![image](https://user-images.githubusercontent.com/34520941/201358112-f0fc258b-4637-40bc-897c-86cda6cd6f05.png)
