### ISSUE TITLE
Create Mantine palette

### ISSUE THREAD

**Issue by web-devel** [react-buddy/ide-toolbox#39]
https://mantine.dev/
https://github.com/mantinedev/mantine

* Create `demo-mantine` project with a palette containing Mantine components. See https://github.com/react-buddy/demo-chakra-ui for example.
* Create mantine package in this repo

**Comment by web-devel** [comment]
* Remove unused imports and Popover from App.tsx
* `AspectRatio` component has wrong documentation link.
* Remove variants which are the same as default (e.g. Button - filled, ActionIcon - transparent)
* Checkbox - with color/Chip - with color - add checked state by default (to see what is color)
* Tabs - contentd ?
* `Data display` -> `Data Display`
* `Progress` and `Divider` previews do not work

**Comment by lovtsovaik** [comment]
see notes in doc
