### ISSUE TITLE
Add an ability to specify style and className for palette containers

### ISSUE THREAD

**Issue by web-devel** [react-buddy/ide-toolbox#44]
For all palette components (`Palette`, `Category`, `Component`, `Variant`) add `style` and `className` props which should be forwarded to DOM elements (containers)

**Comment by lovtsovaik** [comment]
classes:
![classes](https://user-images.githubusercontent.com/73226373/200816110-270bf958-e02a-40ae-b285-ef6aa1e8c9df.PNG)

styles:
![styles](https://user-images.githubusercontent.com/73226373/200816113-57a7ceac-1064-470b-a6aa-55b140137ffc.PNG)
