### ISSUE TITLE
Add more variants to react-intl components

### ISSUE THREAD

**Issue by web-devel** [react-buddy/ide-toolbox#59]
```
- FormattedMessage
   - FormattedMessage
   - FormattedMessage (with default value)
   - FormattedMessage (with values)   
   - ...
```

**Comment by lovtsovaik** [comment]
Now palette contains this elements:
![image](https://user-images.githubusercontent.com/73226373/203750755-29e9426e-21db-4b7a-8a37-a4565d2a5104.png)
(and some other variant of useIntl)

**Comment by lovtsovaik** [comment]
These variant of useIntl are equal:

<Variant name="format time" proto={UseIntlFormatTimeProto} />
<Variant name="format date time range" proto={UseIntlFormatTimeProto} />
