### ISSUE TITLE
Provide palettes for antd and mui as packages

### ISSUE THREAD

**Issue by web-devel** [react-buddy/ide-toolbox#6]
As react-buddy user, i want to use palettes with material ui and ant design components as external npm packages

**Comment by karandashovrz** [comment]
Palettes with mui and antd components implemented in next packages:
@react-buddy/palette-mui 1.0.0-dev.0
@react-buddy/palette-antd 1.0.0-dev0.

**Comment by owlet1997** [comment]
Imported palettes are not displayed:
![image](https://user-images.githubusercontent.com/45730069/154675636-6e0bbd29-ac8b-4d50-876e-83dc66629f94.png)
![image](https://user-images.githubusercontent.com/45730069/154675778-e4ebee41-bae3-4d1e-818a-4d34748140d9.png)

**Comment by karandashovrz** [comment]
Fixed in
@react-buddy/palette-mui 1.0.0-dev.1
@react-buddy/palette-antd 1.0.0-dev.1

**Comment by owlet1997** [comment]
update the peerDependencies version for the "@react-buddy/ide-toolbox" package
**AR:**
"@react-buddy/ide-toolbox": "^1.1.0"
**ER:**
"@react-buddy/ide-toolbox": "^2.0.0"
